/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.javaserviceautowiring.sv_getalltypes.controller;

import com.javaserviceautowiring.sv_getalltypes.SV_GetAllTypes;
import org.springframework.data.domain.Pageable;
import com.javaserviceautowiring.dbscenarios.models.query.SvGetAllTypesResponse;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sV_GetAllTypes")
public class SV_GetAllTypesController {

    @Autowired
    private SV_GetAllTypes sV_GetAllTypes;

    @RequestMapping(value = "/allTypes", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public Page<SvGetAllTypesResponse> getAllTypes(Pageable pageable) {
        return sV_GetAllTypes.getAllTypes(pageable);
    }
}
