/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.javaserviceautowiring.sv_insertwithblob.controller;

import com.javaserviceautowiring.sv_insertwithblob.SV_InsertWithBlob;
import com.javaserviceautowiring.dbscenarios.models.query.SvInsertWithBlobRequest;
import org.springframework.web.multipart.MultipartFile;
import java.lang.Integer;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sV_InsertWithBlob")
public class SV_InsertWithBlobController {

    @Autowired
    private SV_InsertWithBlob sV_InsertWithBlob;

    @RequestMapping(value = "/insertQuery", method = RequestMethod.POST, consumes = "multipart/form-data")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public Integer insertQuery(@RequestPart(value = "svInsertWithBlobRequest") SvInsertWithBlobRequest svInsertWithBlobRequest, @RequestPart(value = "blobcol") MultipartFile blobcol) {
        return sV_InsertWithBlob.insertQuery(svInsertWithBlobRequest, blobcol);
    }
}
