/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.javaserviceautowiring.sv_getloggingbypkid.controller;

import com.javaserviceautowiring.sv_getloggingbypkid.SV_GetLoggingByPkId;
import com.javaserviceautowiring.dbscenarios.models.query.SvGetLoggedInIdByPkIdResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sV_GetLoggingByPkId")
public class SV_GetLoggingByPkIdController {

    @Autowired
    private SV_GetLoggingByPkId sV_GetLoggingByPkId;

    @RequestMapping(value = "/loggedInIdByPk", method = RequestMethod.GET)
    public SvGetLoggedInIdByPkIdResponse getLoggedInIdByPk() {
        return sV_GetLoggingByPkId.getLoggedInIdByPk();
    }
}
