/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.javaserviceautowiring.sv_insertquery.controller;

import com.javaserviceautowiring.sv_insertquery.SV_InsertQuery;
import com.javaserviceautowiring.dbscenarios.models.query.SvInsertQueryRequest;
import java.lang.Integer;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sV_InsertQuery")
public class SV_InsertQueryController {

    @Autowired
    private SV_InsertQuery sV_InsertQuery;

    @RequestMapping(value = "/insertQuery", method = RequestMethod.POST)
    public Integer insertQuery(@RequestBody SvInsertQueryRequest svInsertQueryRequest) {
        return sV_InsertQuery.insertQuery(svInsertQueryRequest);
    }
}
