/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.javaserviceautowiring.sv_alltypeswithspaces.controller;

import com.javaserviceautowiring.sv_alltypeswithspaces.SV_AllTypesWithSpaces;
import org.springframework.data.domain.Pageable;
import com.javaserviceautowiring.dbscenarios.models.query.SvAllTypesWithoutSpaceResponse;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sV_AllTypesWithSpaces")
public class SV_AllTypesWithSpacesController {

    @Autowired
    private SV_AllTypesWithSpaces sV_AllTypesWithspaces;

    @RequestMapping(value = "/allTypesWithoutSpaces", method = RequestMethod.GET)
    public Page<SvAllTypesWithoutSpaceResponse> getAllTypesWithoutSpaces(Pageable pageable) {
        return sV_AllTypesWithspaces.getAllTypesWithoutSpaces(pageable);
    }
}
