/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.javaserviceautowiring.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;

import com.javaserviceautowiring.dbscenarios.models.procedure.*;

public interface DbscenariosProcedureExecutorService {

    ProcedureInsertAndGetQueryResponse executeProcedure_InsertAndGetQuery(ProcedureInsertAndGetQueryRequest procedureInsertAndGetQueryRequest);

    Void executeProcedure_SingleBlobInsert(ProcedureSingleBlobInsertRequest procedureSingleBlobInsertRequest);

    ProcedureGetAllTypesWithAliasesInsertQueryResponse executeProcedure_getAllTypesWithAliases_InsertQuery(ProcedureGetAllTypesWithAliasesInsertQueryRequest procedureGetAllTypesWithAliasesInsertQueryRequest);

    ProcedureGetByCurrentDateResponse executeProcedure_GetByCurrentDate(Date datecol);

    ProcedureGetAllTypesWithAliasesResponse executeProcedure_getAllTypesWithAliases();

    ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsResponse executeProcedure_getAllTypesWithAliases_InsertQueryWithSysParams(ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest);

    Void executeProcedure_InBlob2(ProcedureInBlob2Request procedureInBlob2request);

    Void executeProcedure_AllBlobsInsert(ProcedureAllBlobsInsertRequest procedureAllBlobsInsertRequest);

}


