/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.javaserviceautowiring.db123__;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Blobtypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BLOBTYPES`")
public class Blobtypes implements Serializable {

    private Integer pkid;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol1;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol2;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol3;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol4;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol5;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`PKID`", nullable = false, scale = 0, precision = 10)
    public Integer getPkid() {
        return this.pkid;
    }

    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    @Column(name = "`BLOBCOL1`", nullable = true)
    public byte[] getBlobcol1() {
        return this.blobcol1;
    }

    public void setBlobcol1(byte[] blobcol1) {
        this.blobcol1 = blobcol1;
    }

    @Column(name = "`BLOBCOL2`", nullable = true)
    public byte[] getBlobcol2() {
        return this.blobcol2;
    }

    public void setBlobcol2(byte[] blobcol2) {
        this.blobcol2 = blobcol2;
    }

    @Column(name = "`BLOBCOL3`", nullable = true)
    public byte[] getBlobcol3() {
        return this.blobcol3;
    }

    public void setBlobcol3(byte[] blobcol3) {
        this.blobcol3 = blobcol3;
    }

    @Column(name = "`BLOBCOL4`", nullable = true)
    public byte[] getBlobcol4() {
        return this.blobcol4;
    }

    public void setBlobcol4(byte[] blobcol4) {
        this.blobcol4 = blobcol4;
    }

    @Column(name = "`BLOBCOL5`", nullable = true)
    public byte[] getBlobcol5() {
        return this.blobcol5;
    }

    public void setBlobcol5(byte[] blobcol5) {
        this.blobcol5 = blobcol5;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Blobtypes)) return false;
        final Blobtypes blobtypes = (Blobtypes) o;
        return Objects.equals(getPkid(), blobtypes.getPkid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkid());
    }
}

