/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.javaserviceautowiring.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

public class ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest implements Serializable {


    @JsonProperty("SHORTCOL")
    @NotNull
    private Short shortcol;

    @JsonProperty("INTCOL")
    @NotNull
    private Integer intcol;

    @JsonProperty("LONGCOL")
    @NotNull
    private Long longcol;

    @JsonProperty("FLOATCOL")
    @NotNull
    private Float floatcol;

    @JsonProperty("DOUBLECOL")
    @NotNull
    private Double doublecol;

    @JsonProperty("BIGDECCOL")
    @NotNull
    private BigDecimal bigdeccol;

    @JsonProperty("BIGINTCOL")
    @NotNull
    private BigInteger bigintcol;

    @JsonProperty("CHARCOL")
    @NotNull
    private Character charcol;

    @JsonProperty("CLOBCOL")
    @NotNull
    private String clobcol;

    @JsonProperty("TEXTCOL")
    @NotNull
    private String textcol;

    @JsonProperty("TIMESTAMPCOL")
    @NotNull
    private Timestamp timestampcol;

    @JsonProperty("BOOLEANCOL")
    @NotNull
    private Boolean booleancol;

    @JsonProperty(value = "BLOBCOL", access = Access.READ_ONLY)
    private byte[] blobcol;

    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    public Integer getIntcol() {
        return this.intcol;
    }

    public void setIntcol(Integer intcol) {
        this.intcol = intcol;
    }

    public Long getLongcol() {
        return this.longcol;
    }

    public void setLongcol(Long longcol) {
        this.longcol = longcol;
    }

    public Float getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(Float floatcol) {
        this.floatcol = floatcol;
    }

    public Double getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(Double doublecol) {
        this.doublecol = doublecol;
    }

    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    public Character getCharcol() {
        return this.charcol;
    }

    public void setCharcol(Character charcol) {
        this.charcol = charcol;
    }

    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    public Timestamp getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(Timestamp timestampcol) {
        this.timestampcol = timestampcol;
    }

    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    public byte[] getBlobcol() {
        return this.blobcol;
    }

    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest)) return false;
        final ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest = (ProcedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest) o;
        return Objects.equals(getShortcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getShortcol()) &&
                Objects.equals(getIntcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getIntcol()) &&
                Objects.equals(getLongcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getLongcol()) &&
                Objects.equals(getFloatcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getFloatcol()) &&
                Objects.equals(getDoublecol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getDoublecol()) &&
                Objects.equals(getBigdeccol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getBigdeccol()) &&
                Objects.equals(getBigintcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getBigintcol()) &&
                Objects.equals(getCharcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getCharcol()) &&
                Objects.equals(getClobcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getClobcol()) &&
                Objects.equals(getTextcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getTextcol()) &&
                Objects.equals(getTimestampcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getTimestampcol()) &&
                Objects.equals(getBooleancol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getBooleancol()) &&
                Objects.equals(getBlobcol(), procedureGetAllTypesWithAliasesInsertQueryWithSysParamsRequest.getBlobcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShortcol(),
                getIntcol(),
                getLongcol(),
                getFloatcol(),
                getDoublecol(),
                getBigdeccol(),
                getBigintcol(),
                getCharcol(),
                getClobcol(),
                getTextcol(),
                getTimestampcol(),
                getBooleancol(),
                getBlobcol());
    }
}
