/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.javaserviceautowiring.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

public class ProcedureAllBlobsInsertRequest implements Serializable {


    @JsonProperty(value = "BLOBTYPE1", access = Access.READ_ONLY)
    private byte[] blobtype1;

    @JsonProperty(value = "BLOBTYPE2", access = Access.READ_ONLY)
    private byte[] blobtype2;

    @JsonProperty(value = "BLOBTYPE3", access = Access.READ_ONLY)
    private byte[] blobtype3;

    @JsonProperty(value = "BLOBTYPE4", access = Access.READ_ONLY)
    private byte[] blobtype4;

    @JsonProperty(value = "BLOBTYPE5", access = Access.READ_ONLY)
    private byte[] blobtype5;

    @JsonProperty("BOOLEANCOL")
    @NotNull
    private Boolean booleancol;

    public byte[] getBlobtype1() {
        return this.blobtype1;
    }

    public void setBlobtype1(byte[] blobtype1) {
        this.blobtype1 = blobtype1;
    }

    public byte[] getBlobtype2() {
        return this.blobtype2;
    }

    public void setBlobtype2(byte[] blobtype2) {
        this.blobtype2 = blobtype2;
    }

    public byte[] getBlobtype3() {
        return this.blobtype3;
    }

    public void setBlobtype3(byte[] blobtype3) {
        this.blobtype3 = blobtype3;
    }

    public byte[] getBlobtype4() {
        return this.blobtype4;
    }

    public void setBlobtype4(byte[] blobtype4) {
        this.blobtype4 = blobtype4;
    }

    public byte[] getBlobtype5() {
        return this.blobtype5;
    }

    public void setBlobtype5(byte[] blobtype5) {
        this.blobtype5 = blobtype5;
    }

    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureAllBlobsInsertRequest)) return false;
        final ProcedureAllBlobsInsertRequest procedureAllBlobsInsertRequest = (ProcedureAllBlobsInsertRequest) o;
        return Objects.equals(getBlobtype1(), procedureAllBlobsInsertRequest.getBlobtype1()) &&
                Objects.equals(getBlobtype2(), procedureAllBlobsInsertRequest.getBlobtype2()) &&
                Objects.equals(getBlobtype3(), procedureAllBlobsInsertRequest.getBlobtype3()) &&
                Objects.equals(getBlobtype4(), procedureAllBlobsInsertRequest.getBlobtype4()) &&
                Objects.equals(getBlobtype5(), procedureAllBlobsInsertRequest.getBlobtype5()) &&
                Objects.equals(getBooleancol(), procedureAllBlobsInsertRequest.getBooleancol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBlobtype1(),
                getBlobtype2(),
                getBlobtype3(),
                getBlobtype4(),
                getBlobtype5(),
                getBooleancol());
    }
}
